name: Docker Image CI For [aceaura/whales:{{ .Env.tag }}]

on:
  push:
    branches: ["master"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: { { .Env.username } }
          password: { { .Env.password } }
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: aceaura/whales:{{ .Env.tag }}
